import { User, InventoryItem, StockActivity, ApprovalTicket, MaintenanceTask, TechnicalDocument } from './types';

export const INITIAL_USER: User = {
  id: 'usr-001',
  name: 'Admin User',
  username: 'admin.sontra',
  role: 'Quản trị viên',
  roleBadge: 'QUẢN TRỊ VIÊN',
  initials: 'AD',
  avatarUrl: 'https://lh3.googleusercontent.com/aida/AEtjO1Xi0pevm34gCOdYmjV9rWxCu6S7Kp-wrRnYBA812DXY2HTICbeZiaDVibTfAC-23KwGHPet8G9Rj97QZ7CUcp6JGZVn7aCxq8izK8rECTC62MF--qd0ttXr5ezdscZRk7LgzMuBhLhCTf331-R84dJiIPdQ9g_d_xzSSYfhrAIdx80g5_evmLG_2eUqYcMwcvgeAC8l1hxR3IyWkD2YbMSDJcoof54-vh0_mT37AVdCTuq2lPGxUB_E_yhJZCIh-TQKciAR_sSMlA',
  department: 'Ban Kỹ Thuật & Sửa Chữa (KTSC)',
  plant: 'Nhà máy thủy điện Sơn Trà 1',
};

export const INITIAL_ACTIVITIES: StockActivity[] = [
  {
    id: 'act-001',
    time: '10:45 AM, Hôm nay',
    action: 'Xuất kho',
    item: 'Bơm mỡ tự động',
    itemCode: 'BM-2023-AUTO',
    quantity: 2,
    unit: 'bộ',
    ticketCode: 'XK-2023-08-01',
    user: {
      name: 'Nguyễn Văn A',
      initials: 'NT',
      avatarColor: 'bg-[#d3e4ff] text-[#001c38]',
    },
    status: 'HOÀN THÀNH',
    dateLabel: '10:45',
    notes: 'Xuất cấp cho tổ máy H1 thay thế định kỳ van bypass',
    plant: 'Nhà máy thủy điện Sơn Trà 1',
  },
  {
    id: 'act-002',
    time: '09:15 AM, Hôm nay',
    action: 'Nhập kho',
    item: 'Lọc gió công nghiệp',
    itemCode: 'LG-CN-450',
    quantity: 20,
    unit: 'cái',
    ticketCode: 'NK-2023-08-02',
    user: {
      name: 'Trần Thị B',
      initials: 'TB',
      avatarColor: 'bg-[#d5e3ff] text-[#001b3c]',
    },
    status: 'HOÀN THÀNH',
    dateLabel: '09:15',
    notes: 'Nhập kho theo hợp đồng cung ứng quý 3/2023',
    plant: 'Nhà máy thủy điện Sơn Trà 1',
  },
  {
    id: 'act-003',
    time: '16:30 PM, Hôm qua',
    action: 'Duyệt phiếu nhập',
    item: 'Dầu nhớt động cơ',
    itemCode: 'DN-CAS-68',
    quantity: 5,
    unit: 'thùng (200L)',
    ticketCode: 'NK-2023-08-03',
    user: {
      name: 'Lê Văn C',
      initials: 'LC',
      avatarColor: 'bg-[#d6e3ff] text-[#001b3d]',
    },
    status: 'ĐÃ DUYỆT',
    dateLabel: 'Hôm qua',
    notes: 'Dầu thủy lực ISO VG 68 bôi trơn ổ trục tuabin',
    plant: 'Nhà máy thủy điện Sơn Trà 1',
  },
  {
    id: 'act-004',
    time: '14:00 PM, Hôm qua',
    action: 'Yêu cầu nhập gấp',
    item: 'Cảm biến nhiệt độ',
    itemCode: 'CB-PT100-ST',
    quantity: 8,
    unit: 'cái',
    ticketCode: 'YC-2023-07-29',
    user: {
      name: 'Hệ thống tự động',
      initials: 'AD',
      avatarColor: 'bg-[#ffdad6] text-[#93000a]',
    },
    status: 'CHỜ XỬ LÝ',
    dateLabel: 'Hôm qua',
    notes: 'Cảnh báo mức tồn dưới ngưỡng an toàn (hiện còn 2 chiếc)',
    plant: 'Nhà máy thủy điện Sơn Trà 1',
  },
  {
    id: 'act-005',
    time: '10:45 AM, 01/08',
    action: 'Xuất kho',
    item: 'Vòng bi SKF',
    itemCode: 'VB-SKF-6318',
    quantity: 4,
    unit: 'chiếc',
    ticketCode: 'XK-2023-08-01',
    user: {
      name: 'Nguyễn Văn A',
      initials: 'NT',
      avatarColor: 'bg-[#d3e4ff] text-[#001c38]',
    },
    status: 'HOÀN THÀNH',
    dateLabel: '10:45',
    notes: 'Xuất cho tổ bảo dưỡng ổ đỡ hướng tuabin',
    plant: 'Hòa Bình Plant',
  },
  {
    id: 'act-006',
    time: '09:30 AM, 02/08',
    action: 'Nhập kho',
    item: 'Dầu nhớt Castrol',
    itemCode: 'DN-CAS-HYS',
    quantity: 12,
    unit: 'thùng',
    ticketCode: 'NK-2023-08-02',
    user: {
      name: 'Trần Thị B',
      initials: 'TB',
      avatarColor: 'bg-[#d5e3ff] text-[#001b3c]',
    },
    status: 'HOÀN THÀNH',
    dateLabel: '09:30',
    notes: 'Dầu Castrol Hyspin AWH-M 46 chất lượng cao',
    plant: 'Hòa Bình Plant',
  },
  {
    id: 'act-007',
    time: 'Hôm qua',
    action: 'Xuất kho',
    item: 'Gioăng cao su',
    itemCode: 'GC-NBR-90',
    quantity: 30,
    unit: 'vòng',
    ticketCode: 'XK-2023-07-29',
    user: {
      name: 'Lê Văn C',
      initials: 'LC',
      avatarColor: 'bg-[#d6e3ff] text-[#001b3d]',
    },
    status: 'HOÀN THÀNH',
    dateLabel: 'Hôm qua',
    notes: 'Phục vụ đại tu hệ thống làm mát ổ trục',
    plant: 'Hòa Bình Plant',
  },
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: 'inv-001',
    code: 'BM-2023-AUTO',
    name: 'Bơm mỡ tự động',
    category: 'Cơ khí',
    quantity: 18,
    minQuantity: 5,
    maxQuantity: 50,
    unit: 'bộ',
    location: 'Khu A - Kệ 02',
    status: 'normal',
    lastUpdated: '10:45 AM, Hôm nay',
    specs: 'LubePoint EP-2 24VDC, áp suất max 250 bar',
    supplier: 'Lincoln Industrial',
    pricePerUnit: 14500000,
  },
  {
    id: 'inv-002',
    code: 'LG-CN-450',
    name: 'Lọc gió công nghiệp',
    category: 'Vật tư tiêu hao',
    quantity: 45,
    minQuantity: 15,
    maxQuantity: 100,
    unit: 'cái',
    location: 'Khu B - Kệ 01',
    status: 'normal',
    lastUpdated: '09:15 AM, Hôm nay',
    specs: 'Kích thước 450x450x50mm, tiêu chuẩn F7',
    supplier: 'Camfil Farr',
    pricePerUnit: 850000,
  },
  {
    id: 'inv-003',
    code: 'DN-CAS-68',
    name: 'Dầu nhớt động cơ & thủy lực ISO VG 68',
    category: 'Dầu mỡ nhờn',
    quantity: 14,
    minQuantity: 8,
    maxQuantity: 40,
    unit: 'thùng 200L',
    location: 'Kho Dầu số 1',
    status: 'normal',
    lastUpdated: '16:30 PM, Hôm qua',
    specs: 'Castrol Hyspin AWS 68 chống mài mòn',
    supplier: 'Castrol BP Petco',
    pricePerUnit: 12800000,
  },
  {
    id: 'inv-004',
    code: 'CB-PT100-ST',
    name: 'Cảm biến nhiệt độ Pt100',
    category: 'Cảm biến & Đo lường',
    quantity: 2,
    minQuantity: 10,
    maxQuantity: 30,
    unit: 'cái',
    location: 'Khu C - Kệ Điện Tử',
    status: 'critical',
    lastUpdated: '14:00 PM, Hôm qua',
    specs: '3 dây, Class A, dải đo -50 đến +200°C',
    supplier: 'Endress+Hauser',
    pricePerUnit: 3200000,
  },
  {
    id: 'inv-005',
    code: 'VB-SKF-6318',
    name: 'Vòng bi SKF 6318/C3',
    category: 'Cơ khí',
    quantity: 3,
    minQuantity: 8,
    maxQuantity: 20,
    unit: 'chiếc',
    location: 'Khu A - Kệ 05',
    status: 'critical',
    lastUpdated: '10:45 AM, 01/08',
    specs: 'Đường kính trong 90mm, ngoài 190mm',
    supplier: 'SKF Vietnam',
    pricePerUnit: 4800000,
  },
  {
    id: 'inv-006',
    code: 'GC-NBR-90',
    name: 'Gioăng cao su NBR chịu dầu',
    category: 'Vật tư tiêu hao',
    quantity: 85,
    minQuantity: 30,
    maxQuantity: 200,
    unit: 'vòng',
    location: 'Khu B - Kệ 04',
    status: 'normal',
    lastUpdated: 'Hôm qua',
    specs: 'Độ cứng 70 Shore A, dải nhiệt -30°C đến 120°C',
    supplier: 'Parker Hannifin',
    pricePerUnit: 120000,
  },
  {
    id: 'inv-007',
    code: 'RL-SEL-751',
    name: 'Rơ le bảo vệ kỹ thuật số',
    category: 'Điện - Tự động hóa',
    quantity: 4,
    minQuantity: 5,
    maxQuantity: 10,
    unit: 'bộ',
    location: 'Khu C - Tủ Rơle',
    status: 'warning',
    lastUpdated: '3 ngày trước',
    specs: 'SEL-751 Feeder Protection Relay',
    supplier: 'Schweitzer Engineering Labs',
    pricePerUnit: 68000000,
  },
  {
    id: 'inv-008',
    code: 'CB-AP-DRUK',
    name: 'Cảm biến áp suất đường ống áp lực',
    category: 'Cảm biến & Đo lường',
    quantity: 3,
    minQuantity: 6,
    maxQuantity: 15,
    unit: 'chiếc',
    location: 'Khu C - Kệ 02',
    status: 'warning',
    lastUpdated: '4 ngày trước',
    specs: '0 - 100 bar, tín hiệu ra 4-20mA, chuẩn HART',
    supplier: 'Yokogawa',
    pricePerUnit: 9500000,
  },
  {
    id: 'inv-009',
    code: 'CA-HT-22KV',
    name: 'Cáp ngầm trung thế Cu/XLPE/PVC 24kV 3x240',
    category: 'Điện - Tự động hóa',
    quantity: 450,
    minQuantity: 200,
    maxQuantity: 1000,
    unit: 'mét',
    location: 'Kho bãi Cáp ngoài trời',
    status: 'normal',
    lastUpdated: '1 tuần trước',
    specs: 'Tiêu chuẩn TCVN 5935 / IEC 60502-2',
    supplier: 'CADIVI',
    pricePerUnit: 820000,
  },
  {
    id: 'inv-010',
    code: 'VAN-BT-DN400',
    name: 'Van bướm thủy lực điều khiển DN400 PN16',
    category: 'Cơ khí',
    quantity: 2,
    minQuantity: 2,
    maxQuantity: 6,
    unit: 'chiếc',
    location: 'Khu A - Sàn cơ khí nặng',
    status: 'normal',
    lastUpdated: '5 ngày trước',
    specs: 'Thân gang cầu GGG40, đĩa inox 316, gioăng EPDM',
    supplier: 'AVK Valves',
    pricePerUnit: 42000000,
  },
  {
    id: 'inv-011',
    code: 'CH-PIN-12V',
    name: 'Bình ắc quy chì kín khí 12V-150Ah cho dàn DC',
    category: 'Điện - Tự động hóa',
    quantity: 24,
    minQuantity: 30,
    maxQuantity: 80,
    unit: 'bình',
    location: 'Phòng ắc quy DC 220V',
    status: 'warning',
    lastUpdated: '2 ngày trước',
    specs: 'Vision 6FM150-X, tuổi thọ thiết kế 10 năm',
    supplier: 'Vision Battery',
    pricePerUnit: 4600000,
  },
  {
    id: 'inv-012',
    code: 'MO-MD-OMV',
    name: 'Mỡ bôi trơn chịu nước cao cấp',
    category: 'Dầu mỡ nhờn',
    quantity: 6,
    minQuantity: 10,
    maxQuantity: 30,
    unit: 'xô 18kg',
    location: 'Kho Dầu số 1',
    status: 'warning',
    lastUpdated: '6 ngày trước',
    specs: 'Mobilith SHC 220 độ nhớt gốc tổng hợp',
    supplier: 'ExxonMobil',
    pricePerUnit: 3950000,
  }
];

export const INITIAL_APPROVALS: ApprovalTicket[] = [
  {
    id: 'app-001',
    ticketCode: 'YC-2023-07-29',
    type: 'urgent_purchase',
    title: 'Yêu cầu nhập gấp cảm biến nhiệt độ Pt100 cho ổ hướng',
    requester: 'Hệ thống tự động / Kỹ sư trực ca',
    department: 'Ban Vận Hành H1-H2',
    date: '14:00 PM, Hôm qua',
    priority: 'Cao',
    status: 'pending',
    reason: 'Mức tồn kho dưới ngưỡng an toàn (chỉ còn 2 chiếc). Cần 8 chiếc bổ sung để thay thế đợt bảo dưỡng ổ đỡ hướng trên tổ máy H1.',
    items: [
      { name: 'Cảm biến nhiệt độ Pt100 3 dây', code: 'CB-PT100-ST', quantity: 8, unit: 'cái', estimatedCost: '25.600.000 VNĐ' }
    ]
  },
  {
    id: 'app-002',
    ticketCode: 'XK-2023-08-04',
    type: 'export',
    title: 'Phiếu xuất kho rơ le SEL-751 thay thế tủ phân phối 22kV',
    requester: 'Nguyễn Văn A',
    department: 'Đội Điện - SCADA',
    date: '08:30 AM, Hôm nay',
    priority: 'Cao',
    status: 'pending',
    reason: 'Thay thế rơ le ngăn lộ 471 do phát hiện sai số đo lường dòng điện trong đợt kiểm định định kỳ.',
    items: [
      { name: 'Rơ le bảo vệ kỹ thuật số SEL-751', code: 'RL-SEL-751', quantity: 1, unit: 'bộ', estimatedCost: '68.000.000 VNĐ' }
    ]
  },
  {
    id: 'app-003',
    ticketCode: 'NK-2023-08-05',
    type: 'import',
    title: 'Nhập kho lô vật tư gioăng đệm và mỡ chịu nước Mobilith',
    requester: 'Trần Thị B',
    department: 'Tổ Quản Lý Vật Tư',
    date: '11:15 AM, Hôm qua',
    priority: 'Trung bình',
    status: 'pending',
    reason: 'Hàng về theo biên bản giao nhận số 44/BB-DP với nhà cung ứng ExxonMobil.',
    items: [
      { name: 'Mỡ bôi trơn chịu nước Mobilith SHC 220', code: 'MO-MD-OMV', quantity: 10, unit: 'xô 18kg', estimatedCost: '39.500.000 VNĐ' },
      { name: 'Gioăng cao su NBR chịu dầu', code: 'GC-NBR-90', quantity: 50, unit: 'vòng', estimatedCost: '6.000.000 VNĐ' }
    ]
  },
  {
    id: 'app-004',
    ticketCode: 'YC-2023-08-06',
    type: 'urgent_purchase',
    title: 'Mua bổ sung vòng bi SKF 6318/C3 dự phòng khẩn cấp',
    requester: 'Lê Văn C',
    department: 'Ban KTSC',
    date: '2 ngày trước',
    priority: 'Cao',
    status: 'pending',
    reason: 'Chuẩn bị vật tư cho đợt bảo dưỡng cấp 1 tổ máy số 2 (H2) vào tháng tới.',
    items: [
      { name: 'Vòng bi SKF 6318/C3', code: 'VB-SKF-6318', quantity: 6, unit: 'chiếc', estimatedCost: '28.800.000 VNĐ' }
    ]
  },
  {
    id: 'app-005',
    ticketCode: 'XK-2023-08-07',
    type: 'export',
    title: 'Xuất dầu nhớt Castrol bôi trơn hệ thống nâng hạ van cung',
    requester: 'Hoàng Minh D',
    department: 'Tổ Vận Hành Đập & Thủy Công',
    date: '3 ngày trước',
    priority: 'Trung bình',
    status: 'pending',
    reason: 'Bảo trì định kỳ trạm nguồn thủy lực xả tràn trước mùa mưa lũ.',
    items: [
      { name: 'Dầu nhớt Castrol Hyspin AWS 68', code: 'DN-CAS-68', quantity: 2, unit: 'thùng 200L', estimatedCost: '25.600.000 VNĐ' }
    ]
  },
  {
    id: 'app-006',
    ticketCode: 'NK-2023-08-08',
    type: 'import',
    title: 'Nghiệm thu nhập kho bộ van bướm DN400 cấp nước kỹ thuật',
    requester: 'Trần Thị B',
    department: 'Tổ Quản Lý Vật Tư',
    date: '3 ngày trước',
    priority: 'Trung bình',
    status: 'pending',
    reason: 'Đã hoàn thành kiểm tra CO/CQ và thử áp lực tại hiện trường.',
    items: [
      { name: 'Van bướm thủy lực điều khiển DN400 PN16', code: 'VAN-BT-DN400', quantity: 1, unit: 'chiếc', estimatedCost: '42.000.000 VNĐ' }
    ]
  },
  {
    id: 'app-007',
    ticketCode: 'YC-2023-08-09',
    type: 'urgent_purchase',
    title: 'Thay thế 12 bình ắc quy chì kín khí 12V-150Ah phân nhánh 2',
    requester: 'Đặng Quốc T',
    department: 'Đội Điện - Trạm',
    date: '4 ngày trước',
    priority: 'Cao',
    status: 'pending',
    reason: 'Đo nội trở ắc quy phát hiện sụt áp nghiêm trọng ở chuỗi pin số 2 phòng DC.',
    items: [
      { name: 'Bình ắc quy chì 12V-150Ah Vision', code: 'CH-PIN-12V', quantity: 12, unit: 'bình', estimatedCost: '55.200.000 VNĐ' }
    ]
  },
  {
    id: 'app-008',
    ticketCode: 'XK-2023-08-10',
    type: 'export',
    title: 'Xuất lọc gió công nghiệp lắp mới cho buồng máy phát H1',
    requester: 'Phạm Đức E',
    department: 'Đội Vận Hành',
    date: '4 ngày trước',
    priority: 'Thấp',
    status: 'pending',
    reason: 'Thay thế lọc gió bám bụi sau đợt chạy máy cao điểm hè.',
    items: [
      { name: 'Lọc gió công nghiệp 450x450', code: 'LG-CN-450', quantity: 6, unit: 'cái', estimatedCost: '5.100.000 VNĐ' }
    ]
  }
];

export const INITIAL_MAINTENANCE_TASKS: MaintenanceTask[] = [
  {
    id: 'mnt-001',
    code: 'SC-2023-H1-01',
    title: 'Bảo dưỡng định kỳ hệ thống bôi trơn ổ trục tổ máy H1',
    equipment: 'Tổ máy số 1 (Turbine Francis 15MW)',
    plantArea: 'Nhà máy chính - Cao trình +125m',
    priority: 'Cao',
    status: 'Đang sửa chữa',
    assignedTo: 'Nguyễn Văn A (Nhóm Trưởng Cơ Khí)',
    startDate: '2023-08-20',
    estimatedCompletion: '2023-08-25',
    progressPercent: 65,
    description: 'Vệ sinh lưới lọc dầu, kiểm tra bơm mỡ tự động, siết lực bu lông mặt bích van bypass.'
  },
  {
    id: 'mnt-002',
    code: 'SC-2023-TBA-02',
    title: 'Thí nghiệm định kỳ máy cắt và rơ le bảo vệ ngăn lộ 110kV',
    equipment: 'Trạm phân phối 110kV',
    plantArea: 'Trạm ngoài trời 110kV',
    priority: 'Cao',
    status: 'Đang vận hành',
    assignedTo: 'Đặng Quốc T (Kỹ sư Rơ le & Thí nghiệm)',
    startDate: '2023-08-22',
    estimatedCompletion: '2023-08-26',
    progressPercent: 90,
    description: 'Đo điện trở tiếp xúc máy cắt 171, thử nghiệm đặc tuyến rơ le quá dòng và so lệch máy biến áp T1.'
  },
  {
    id: 'mnt-003',
    code: 'SC-2023-DAP-03',
    title: 'Kiểm tra độ kín khít gioăng cao su cửa van đập tràn số 2',
    equipment: 'Cửa van cung đập tràn số 2',
    plantArea: 'Khu vực Đập dâng & Đập tràn',
    priority: 'Trung bình',
    status: 'Chờ vật tư',
    assignedTo: 'Hoàng Minh D (Tổ Vận Hành Đập)',
    startDate: '2023-08-18',
    estimatedCompletion: '2023-08-28',
    progressPercent: 30,
    description: 'Chờ nhận 30 gioăng cao su NBR để thay thế phần đệm đáy bị lão hóa do thời tiết.'
  },
  {
    id: 'mnt-004',
    code: 'SC-2023-SCADA-04',
    title: 'Nâng cấp cấu hình máy chủ SCADA và hệ thống giám sát rung đảo',
    equipment: 'Hệ thống DCS / SCADA Honeywell',
    plantArea: 'Phòng Điều Khiển Trung Tâm (CCR)',
    priority: 'Thấp',
    status: 'Hoàn thành',
    assignedTo: 'Lê Văn C (Trưởng ca)',
    startDate: '2023-08-10',
    estimatedCompletion: '2023-08-15',
    progressPercent: 100,
    description: 'Hiệu chuẩn cảm biến rung ổ trục trên/dưới và đồng bộ dữ liệu thời gian thực về Trung tâm điều độ A3.'
  }
];

export const INITIAL_DOCUMENTS: TechnicalDocument[] = [
  {
    id: 'doc-001',
    code: 'QT-ST1-VH-01',
    title: 'Quy trình vận hành khởi động và dừng tổ máy thủy điện Sơn Trà 1',
    category: 'Quy trình vận hành',
    fileFormat: 'PDF',
    fileSize: '4.8 MB',
    updatedDate: '15/07/2023',
    author: 'Ban KTSC - Công ty CP Sơn Trà Energy',
    version: '3.2 (Ban hành 2023)',
    downloadsCount: 142,
    description: 'Hướng dẫn chi tiết trình tự thao tác đóng mở van đĩa, hòa đồng bộ máy phát lên lưới 110kV.'
  },
  {
    id: 'doc-002',
    code: 'BV-ST1-TB-102',
    title: 'Bản vẽ mặt cắt cấu tạo tua bin Francis trục đứng và hệ thống ổ đỡ',
    category: 'Bản vẽ kỹ thuật',
    fileFormat: 'DWG',
    fileSize: '18.5 MB',
    updatedDate: '02/06/2023',
    author: 'Tập đoàn Dongfang Electric',
    version: 'Rev 4',
    downloadsCount: 88,
    description: 'Bản vẽ thiết kế chi tiết cánh hướng nước, bánh xe công tác runner và trục chính tuabin.'
  },
  {
    id: 'doc-003',
    code: 'ST-SEL751-VIET',
    title: 'Sổ tay kỹ thuật & Hướng dẫn cài đặt cấu hình rơ le bảo vệ SEL-751',
    category: 'Sổ tay thiết bị',
    fileFormat: 'PDF',
    fileSize: '12.1 MB',
    updatedDate: '20/05/2023',
    author: 'Schweitzer Engineering Laboratories',
    version: 'Tiếng Việt 2.0',
    downloadsCount: 95,
    description: 'Tài liệu hướng dẫn lập trình logic ACSELERATOR QuickSet và sơ đồ chân đấu nối nhị thứ.'
  },
  {
    id: 'doc-004',
    code: 'BB-TN-MBA-T1',
    title: 'Biên bản thử nghiệm xuất xưởng và nghiệm thu Máy biến áp 25MVA 11/110kV',
    category: 'Biên bản thử nghiệm',
    fileFormat: 'PDF',
    fileSize: '3.2 MB',
    updatedDate: '10/01/2023',
    author: 'Trung tâm Thí nghiệm điện Miền Trung (ETC)',
    version: 'Bản chính thức',
    downloadsCount: 64,
    description: 'Kết quả đo điện trở cách điện, tỷ số biến áp, tổn hao không tải và thử điện áp tăng cao tần số công nghiệp.'
  },
  {
    id: 'doc-005',
    code: 'QC-AT-2023-ST1',
    title: 'Quy chuẩn an toàn điện và phòng cháy chữa cháy công trình thủy điện',
    category: 'Quy chuẩn an toàn',
    fileFormat: 'DOCX',
    fileSize: '2.1 MB',
    updatedDate: '01/01/2023',
    author: 'Hội đồng An toàn Vệ sinh Lao động Sơn Trà',
    version: 'Ấn bản 2023',
    downloadsCount: 210,
    description: 'Quy định trang bị bảo hộ, phiếu công tác, rào chắn và biện pháp an toàn khi sửa chữa thiết bị điện áp cao.'
  }
];
